### ISSUE TITLE
Error on install OSX 10.12.1

### ISSUE THREAD

**Issue by rob-moore** [wellsjo/JSON-Splora#61]
![screen shot 2016-12-08 at 10 07 59 am](https://cloud.githubusercontent.com/assets/16259450/21019635/7474b7ae-bd2e-11e6-9571-7923edc10c71.png)

I was unable to install through npm. I noticed there was a similar issue here: https://github.com/wellsjo/JSON-Splora/issues/60

However, my error seems to be different. Here's my `npm-debug.log`

```
$ cat /Users/robmoore/npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/Users/robmoore/.nvm/versions/node/v6.9.2/bin/node',
1 verbose cli   '/Users/robmoore/.nvm/versions/node/v6.9.2/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'json-splora' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData json-splora
8 silly fetchNamedPackageData json-splora
9 silly mapToRegistry name json-splora
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'json-splora',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'json-splora',
12 silly mapToRegistry   name: 'json-splora',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/json-splora
14 verbose request uri https://registry.npmjs.org/json-splora
15 verbose request no auth needed
16 info attempt registry request try #1 at 10:07:58 AM
17 verbose request id b9405668eb5d2016
18 verbose etag W/"583dd291-1bf"
19 verbose lastModified Tue, 29 Nov 2016 19:10:09 GMT
20 http request GET https://registry.npmjs.org/json-splora
21 http 304 https://registry.npmjs.org/json-splora
22 verbose headers { date: 'Thu, 08 Dec 2016 17:07:58 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"583dd291-1bf"',
22 verbose headers   age: '277',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-sea1923-SEA',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1481216878.259426,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Thu, 08 Dec 2016 17:07:58 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"583dd291-1bf"',
23 silly get     age: '277',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-sea1923-SEA',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1481216878.259426,VS0,VE0',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/json-splora from cache
25 verbose get saving json-splora to /Users/robmoore/.npm/registry.npmjs.org/json-splora/.cache.json
26 verbose correctMkdir /Users/robmoore/.npm correctMkdir not in flight; initializing
27 verbose stack TypeError: Cannot convert undefined or null to object
27 verbose stack     at pickVersionFromRegistryDocument (/Users/robmoore/.nvm/versions/node/v6.9.2/lib/node_modules/npm/lib/fetch-package-metadata.js:125:29)
27 verbose stack     at /Users/robmoore/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/iferr/index.js:13:50
27 verbose stack     at /Users/robmoore/.nvm/versions/node/v6.9.2/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
27 verbose stack     at saved (/Users/robmoore/.nvm/versions/node/v6.9.2/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
27 verbose stack     at /Users/robmoore/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:241:18
27 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
28 verbose cwd /Users/robmoore
29 error Darwin 16.1.0
30 error argv "/Users/robmoore/.nvm/versions/node/v6.9.2/bin/node" "/Users/robmoore/.nvm/versions/node/v6.9.2/bin/npm" "install" "-g" "json-splora"
31 error node v6.9.2
32 error npm  v3.10.9
33 error Cannot convert undefined or null to object
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]
```

Could this be a versioning issue with my version of node(6.9.2) or npm(3.10.9)? Or possibly my use of nvm?

**Comment by rob-moore** [comment]
Nevermind. The problem came from not capitalizing the name correctly. Closing this ticket.
