### ISSUE TITLE
Tests don't run on first install

### ISSUE THREAD

**Issue by kylealwyn** [wellsjo/JSON-Splora#69]
Steps:
1. Clone project
2. `npm install`
3. `npm test`

Output: 
```
running validate...passed!
running test...failed!
/Users/kyle/Projects/splora/app/js/Editor.js:11
const { EventEmitter } = require('events')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Object.require.extensions.(anonymous function) (/Users/kyle/Projects/splora/node_modules/proxyquire/lib/proxyquire.js:259:43)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Proxyquire._require (/Users/kyle/Projects/splora/node_modules/proxyquire/lib/proxyquire.js:166:19)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/kyle/Projects/splora/app/js/Page.js:12:16)
    at Module._compile (module.js:398:26)
```

**Comment by wellsjo** [comment]
hey @kylealwyn, I think the issue is actually an outdated node version. Which version are you using? "Destructuring" (which is what is breaking) became a feature in V6.

**Comment by kylealwyn** [comment]
Agh, the pains of developing on two machines.
